version: '3'

services:
  postgres:
    image: postgres:14-alpine
    container_name: test-articles
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: work-test-articles
    ports:
      - "7432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
